name = "zuglo-form"
main = "src/workers.ts"
compatibility_date = "2025-10-21"

# Allow CORS only from your site (set after you add the domain)
[vars]
ALLOWED_ORIGIN = "https://zuglo-lutheran-form.com"

# Daily backup at 03:00 UTC (adjust as needed)
[triggers]
crons = ["0 3 * * *"]

# Bind D1
[[d1_databases]]
binding = "DB"
database_name = "developer"
database_id = "7ca26c1a-b88f-4635-85c8-6091f4004b5e"

# Optional: enable R2 backups (comment out if not using)
# [[r2_buckets]]
# binding = "BACKUPS"
# bucket_name = "zuglo-form-backups"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "zuglo-assets"
